# This file is maintained in the Qontigo/devops-gh-actions repo and that copy will overwrite any changes made in any repo using the file

# Checks that the target for a PR is correct based on the name of the source branch.
# e.g.
# feature/XXX PRs can be only be merged to master
# relfix/XXX PRs can only be merged to release/NNN branches
# prod can be merged into master or a release/NNN branch

name: PR Target Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_target:
    uses: Qontigo/devops-gh-actions/.github/workflows/core-pr-target-check.yml@main