name: 'Submodules Sync'
on:
    # Allows you to run this workflow manually from the Actions tab or through HTTP API
    workflow_dispatch:
  
jobs:
    sync:
      name: 'Submodules Sync'
      runs-on: ubuntu-latest
  
      defaults:
        run:
          shell: bash
  
      steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
            token: ${{ secrets.QONTIGO_GH_ACTION_PAT }}
            submodules: true
            ref: ${{ github.ref_name }}
            fetch-depth: 0
  
      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule foreach --recursive git checkout ${{ github.ref_name }}
  
      - name: Commit update
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"